version: "2"

services:
  server:
    build: ./server
    ports:
      - "5555:5555"
    volumes:
      - ./server:/usr/src/app
      # prevents host/container contamination
      - /usr/src/app/node_modules
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    command: npm run dev
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
